### ISSUE TITLE
Auto-build the docker image using kaniko

### ISSUE THREAD

**Issue by fcharras** [soda-inria/sklearn-numba-dpex#29]
We want to auto-build our docker image when a push on the main branch contains changes to the dockerfile (and, later on, only when we issue releases).

Apparently this does not require a premium docker account, it could be done by registering a token in the github panel and using kaniko to build and push the image.

Kaniko [1](https://github.com/GoogleContainerTools/kaniko) [2](https://github.com/marketplace/actions/kaniko-builder) [3](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html)

@jjerphan @ogrisel

**Comment by jjerphan** [comment]
Completed by https://github.com/soda-inria/sklearn-numba-dpex/pull/30.

**Comment by fcharras** [comment]
Not quite, iterations were needed until it worked, I pushed on the main branch to shortcut the tedious testing, this is the final version that actually works:

 https://github.com/soda-inria/sklearn-numba-dpex/blob/main/.github/workflows/run_docker_build.yaml

the script is good now but the build fails, probably there's not enough storage on the runner, the building process is going to require about 15GB. It was a nice try but I don't think we can't get around that easily ? so.. let's remove the workflow and keep it in a PR instead ?

Let me know if you have comments for things I should amend.

**Comment by jjerphan** [comment]
> so.. let's remove the workflow and keep it in a PR instead ?

If it currently fails, I would deactivate/skip it for now (with a reason). WDYT?

**Comment by fcharras** [comment]
I think I can fix the Dockerfile so that it consumes less disk space during build (by using bind mounts rather than  copy), currently experimenting with that

**Comment by fcharras** [comment]
BTW i realized that kaniko is not necessary here, docker is available directly in the ubuntu-latest runner.

**Comment by fcharras** [comment]
Those changes finally makes it work (+ some bumps of the components):

https://github.com/soda-inria/sklearn-numba-dpex/commit/144510a93c183c77362fb7082fde07674856ed27

success pipeline:

https://github.com/soda-inria/sklearn-numba-dpex/actions/runs/3233703875/jobs/5295898476

leaving the issue open for a while if you want to review, we can iterate on the Dockerfile.

**Comment by jjerphan** [comment]
Nice! 

If you've managed to get to a working state for the workflow, can you open a PR to have it in main? Thanks!

**Comment by fcharras** [comment]
It's already in main :-/ I wanted to avoid having to juggle with access tokens and github "Environments" and conditional pipelines (we don't want to push an image in a PR or a branch other than main and there's a small risk of leaking credentials...)

**Comment by jjerphan** [comment]
OK; then if everything works, can we close this issue as completed?

**Comment by fcharras** [comment]
yes! :grin:
