### ISSUE TITLE
Possible typo in `kernels.py:sum_reduction` function

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [soda-inria/sklearn-numba-dpex#54]
https://github.com/soda-inria/sklearn-numba-dpex/blob/main/sklearn_numba_dpex/common/kernels.py#L221-L225

The function reads

```python
def sum_reduction(summands):
    for kernel, result in kernels_and_empty_tensors_pairs:
        kernel(summands, result) 
        summands = result
    return result
```

The returned variable `result` is outside of its scope of definition (local variable defined in the scope of the loop). 

I believe the last line should be `return summands` instead.

**Comment by fcharras** [comment]
I can change this in a PR if it's more readable, but in fact in python the scope of the variables defined in a loop is the same scope that other local variables. 

e.g you can do

```python
for i in range(10):
    pass
print(i)
```

output will be `9`.

BTW we just merged unit tests for the reduction kernels and added a reduction for 2d tensors on axis 1 :grin: 

(See https://github.com/soda-inria/sklearn-numba-dpex/pull/46 for some thinking on using custom kernels vs dpnp functions)

**Comment by oleksandr-pavlyk** [comment]
Thanks for highlighting #46 ! 

I think `return summands` would read better indeed, but its just a suggestion.
