### ISSUE TITLE
Unable to build sklearn-numba-dpex package

### ISSUE THREAD

**Issue by Vika-F** [soda-inria/sklearn-numba-dpex#56]
**Short description**
An error occurs when I run kmeans.py benchmark:
RuntimeError: Could not find any provider for the sklearn_engines entry point with name(s): 'sklearn_numba_dpex'

**Steps to reproduce**

### create dppy-dev-v2 env and install dppy-dev
```
conda create -n dppy-dev-v2 dpctl=0.14* dpnp numba numba-dpex -c dppy/label/dev -c intel
conda activate dppy-dev-v2
. /opt/intel/oneapi/compiler/latest/env/vars.sh
. /opt/intel/oneapi/tbb/latest/env/vars.sh intel64
export PATH=/opt/intel/oneapi/compiler/latest/linux/bin-llvm:$PATH
git clone https://github.com/IntelPython/numba-dpex/
cd numba-dpex
pip install -e . --no-build-isolation
cd ..
```
### install wip-engines
```
git clone https://github.com/ogrisel/scikit-learn -b wip-engines
conda install -c intel scipy pandas
pip install --no-cache-dir cython
pip install -e . --no-build-isolation --no-cache-dir
cd ..
```
### install sklearn-numba-dpex
```
git clone https://github.com/soda-inria/sklearn-numba-dpex
cd sklearn-numba-dpex
pip install -e . --no-build-isolation
```
### run K-means
```
cd benchmark
python kmeans.py
```
The behaviour is reproduced on Windows Subsystem for Linux (WSL), Ubuntu 20.04

**Comment by fcharras** [comment]
Hi @Vika-F thank you for the report. I've just checked that on main branch the script works when ran within the provided docker image so the issue is somewhere among the differences in the install process. On the go I don't see anything wrong but we don't test with those commands on our side and we know installation is a main pain point at the moment. (and i'm less familiar with conda myself)

The error message seems to indicate that the entry point defined in the setup instructions of `sklearn_numba_dpex` (`pyproject.toml` file) is not properly registered during setup.

Can you check that the `sklearn_numba_dpex` package is importable in your environment ? (try running `python -c "import sklearn_numba_dpex"`) ? and if not, same but after deactivating / reactivating the conda environment ?

I can try to reproduce, I assume that you use latest commits from `sklearn_numba_dpex` / the `wip-engines` branch, not sure about python version: is it system python or some other python install in the conda env ? we test with python 3.9.13.

Would you like trying to debug it live with voicechat ?

**Comment by Vika-F** [comment]
Hi @fcharras , thank you for the prompt responce.
It seems that `sklearn_numba_dpex` is not available in my conda environment. `python -c "import sklearn_numba_dpex"` produces the same error when I activate dppy-dev-v2 environment and also after `conda deactivate` + `conda activate dppy-dev-v2`.

But pip install of the package had completed successfully as far as I can see:
```
(dppy-dev-v2) username@username-mobl2:~/code/inria/v2/sklearn-numba-dpex$ pip install -e . --no-build-isolation
Obtaining file:///home/username/code/inria/v2/sklearn-numba-dpex
  Checking if build backend supports build_editable ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
  Running setup.py develop for UNKNOWN
**Successfully installed UNKNOWN-0.0.0**
```

Is it Ok by the way that the package name is "unknown"?

> I assume that you use latest commits from sklearn_numba_dpex / the wip-engines branch,

Actually no, as I faced this issue about a week ago. But I will repeat the steps with the latest versions and report about the status.

Python version is also a bit outdated: Python 3.9.12 :: Intel Corporation

> Would you like trying to debug it live with voicechat ?
Sure, that will be great.

**Comment by fcharras** [comment]
`UNKNOWN` doesn't sound OK, it sounds like a part of the issue, here's what I get:

```
Successfully built sklearn-numba-dpex
Installing collected packages: sklearn-numba-dpex
Successfully installed sklearn-numba-dpex-0.1.0.dev0
```

A few ideas:

- try [upgrading setuptools](https://stackoverflow.com/a/54744879) with `pip install -U setuptools` before installing
- `Python 3.9.12` should be fine but are there changes coming from the `:: Intel Corporation` regarding packaging and installing ? maybe try another python distribution in the conda env ?
- try other installation commands: 
  - either no editable mode (without `-e` in `pip install commands)
  - or try `python setup.py develop` / `python setup.py install`

Do you have the same issue with the scikit-learn install ?

**Comment by Vika-F** [comment]
I have removed old versions of dppy-dev environments, updated my conda (just in case, and now I have Python 3.9.13) and tried to do a clean build.

First, there was a problem with llvmlite package.
I did the following (without `-e` in `pip install`):

```
conda create -n dppy-dev dpctl=0.14* dpnp numba numba-dpex -c dppy/label/dev -c intel
conda activate dppy-dev
pip install cython
. /opt/intel/oneapi/compiler/latest/env/vars.sh
. /opt/intel/oneapi/tbb/latest/env/vars.sh intel64
export PATH=/opt/intel/oneapi/compiler/latest/linux/bin-llvm:$PATH
git clone https://github.com/IntelPython/numba-dpex/
cd numba-dpex
pip install . --no-build-isolation
```

And got this error:
(dppy-dev) username@username-mobl2:~/code/inria/v5/numba-dpex$ pip install . --no-build-isolation
Processing /home/username/code/inria/v5/numba-dpex
  Preparing metadata (pyproject.toml) ... done
Collecting numba>=0.56
  Using cached numba-0.56.4-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
Requirement already satisfied: dpctl in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from numba-dpex==0.19.0.dev0) (0.14.0rc2+16.g05c358ee0)
Requirement already satisfied: packaging in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from numba-dpex==0.19.0.dev0) (21.3)
Collecting llvmlite<0.40,>=0.39.0dev0
  Using cached llvmlite-0.39.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
Requirement already satisfied: numpy<1.24,>=1.18 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from numba>=0.56->numba-dpex==0.19.0.dev0) (1.21.4)
Requirement already satisfied: setuptools in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from numba>=0.56->numba-dpex==0.19.0.dev0) (58.0.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from packaging->numba-dpex==0.19.0.dev0) (3.0.9)
Building wheels for collected packages: numba-dpex
  Building wheel for numba-dpex (pyproject.toml) ... done
  Created wheel for numba-dpex: filename=numba_dpex-0.19.0.dev0-cp39-cp39-linux_x86_64.whl size=300630 sha256=9ac011b2d28daa59fbaac61fe83456208fb398516c567c7b62b2ca8ea0f460c9
  Stored in directory: /home/username/.cache/pip/wheels/f5/40/31/6f619908edc9d65f907f914bd86598344781b67c727917d3bf
**Successfully built numba-dpex**
Installing collected packages: llvmlite, numba, numba-dpex
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.38.1+0.g650c36d.dirty
**ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**

So, I've tried `pip install . --no-build-isolation --ignore-installed llvmlite`. That was successful.

Installation of `wip-engines` and `sklearn_numba_dpex` also was successful, both without `-e` flags.

But I saw that numpy was re-installed during the installation of wip-engines:

username@username-mobl2:~/code/inria/v5/scikit-learn$ pip install . --no-build-isolation --no-cache-dir
Processing /home/username/code/inria/v5/scikit-learn
  Preparing metadata (pyproject.toml) ... done
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=1.1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 4.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17.3 in /home/vsfedoto/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from scikit-learn==1.2.dev0) (1.23.4)
Requirement already satisfied: scipy>=1.3.2 in /home/vsfedoto/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from scikit-learn==1.2.dev0) (1.7.3)
Collecting numpy>=1.17.3
  **Downloading numpy-1.22.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)**
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 7.3 MB/s eta 0:00:00
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (pyproject.toml) ... done
  Created wheel for scikit-learn: filename=scikit_learn-1.2.dev0-cp39-cp39-linux_x86_64.whl size=18714329 sha256=113ec8ef17381699ba5d3a4be22accfe33e40bd86aebbb4b487a6ed678b307eb
  Stored in directory: /tmp/pip-ephem-wheel-cache-w_go2w6g/wheels/69/7c/2d/0f55f9f04d850e4b7f1932a002d4500d1462a6b8506d3ad914
Successfully built scikit-learn
Installing collected packages: threadpoolctl, numpy, joblib, scikit-learn
  **Attempting uninstall: numpy
    Found existing installation: numpy 1.23.4
    Uninstalling numpy-1.23.4:
      Successfully uninstalled numpy-1.23.4**
Successfully installed joblib-1.2.0 numpy-1.22.4 scikit-learn-1.2.dev0 threadpoolctl-3.1.0


As the result, now I can successfully import `sklearn_numba_dpex`, but I see the error related to `numpy` versions inconsistency when running kmeans.py benchmark.

**Comment by Vika-F** [comment]
Here is the numpy error:
(dppy-dev) username@username-mobl2:~/code/inria/v5/sklearn-numba-dpex/benchmark$ python kmeans.py 
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/code/inria/v5/sklearn-numba-dpex/benchmark/kmeans.py", line 5, in <module>
    import sklearn
  File "/home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages/sklearn/utils/__init__.py", line 19, in <module>
    from .murmurhash import murmurhash3_32
  File "sklearn/utils/murmurhash.pyx", line 26, in init sklearn.utils.murmurhash
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

**Comment by Vika-F** [comment]
I will try to create the initial dppy-dev environment with numpy=1.22.4. I think it might help.
I will report about the results.

**Comment by Vika-F** [comment]
I tried several more times to build sklearn-numba-dpex. Still no success.
I have consulted with @oleksandr-pavlyk and he said that there is no need now in building numba-dpex as I can use numba-dpex installed from conda.

So, my latest steps to build sklearn-numba-dpex look like this.

**Step 1. Prepare dppy-dev package**
```
conda create -n dppy-dev dpctl=0.14* dpnp numba numba-dpex cython spirv-tools scipy pandas -c dppy/label/dev -c intel --override-channels
```

** Step 2. Activate dppy-dev environment**
```
conda activate dppy-dev
```

** Step 3. Setup compiler environment**
```
source /opt/intel/oneapi/compiler/latest/env/vars.sh
source /opt/intel/oneapi/tbb/latest/env/vars.sh intel64
export PATH=/opt/intel/oneapi/compiler/latest/linux/bin-llvm:$PATH
```

**Step 4. Install wip-engines**
```
git clone https://github.com/ogrisel/scikit-learn -b wip-engines
cd scikit-learn
pip install . --no-build-isolation
cd ..
```

This package was built successfully. Here is the log:
```
Processing /home/username/code/inria/scikit-learn
  Preparing metadata (pyproject.toml) ... done
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=1.1.1
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Requirement already satisfied: numpy>=1.17.3 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from scikit-learn==1.2.dev0) (1.21.4)
Requirement already satisfied: scipy>=1.3.2 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from scikit-learn==1.2.dev0) (1.7.3)
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (pyproject.toml) ... done
  Created wheel for scikit-learn: filename=scikit_learn-1.2.dev0-cp39-cp39-linux_x86_64.whl size=18626435 sha256=8c87ae039d17c7055b131809e20d1aea5b0257f6381395b07d43789fad5587b8
  Stored in directory: /home/username/.cache/pip/wheels/d7/e0/78/c9f73679413ce804a592d2de32d0af04c2878d67f1ebd4defc
Successfully built scikit-learn
Installing collected packages: threadpoolctl, joblib, scikit-learn
Successfully installed joblib-1.2.0 scikit-learn-1.2.dev0 threadpoolctl-3.1.0
```

**Step 5. Install sklearn-numba-dpex**
```
git clone https://github.com/soda-inria/sklearn-numba-dpex
cd sklearn-numba-dpex
pip install . --no-build-isolation
```

And here the strange thing happens:
```
Processing /home/username/code/inria/sklearn-numba-dpex
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=2200 sha256=824953ff59293cae0436bcb64b6fb22f5b97a410f03715a242792540e415d8d9
  Stored in directory: /home/username/.cache/pip/wheels/9c/49/69/06110ec83c2803d5cdeaadd5318c80946a8c6574a3e6737dcb
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```

I also tried to use `pip install -U setuptools`, but this didn't help. The result is the same.
`conda deactivate` + `conda activate dppy-dev` also didn't help.

Have you any ideas how to debug this?

**Comment by Vika-F** [comment]
I've just got some progress with sklearn-numba-dpex. But still getting errors with kmeans.py.

`pip install setuptools --upgrade` helped to build the package.

Here is the log. Can you please take a look? Is it Ok?
```
Processing /home/username/code/inria/sklearn-numba-dpex
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scikit-learn in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from sklearn-numba-dpex==0.1.0.dev0) (1.2.dev0)
Requirement already satisfied: numba-dpex in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from sklearn-numba-dpex==0.1.0.dev0) (0.18.1+50.g219ec1cd)
Requirement already satisfied: dpctl in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from sklearn-numba-dpex==0.1.0.dev0) (0.14.0+6.g769095261)
Requirement already satisfied: numpy in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from dpctl->sklearn-numba-dpex==0.1.0.dev0) (1.21.4)
Requirement already satisfied: numba<0.56,>=0.54.0 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from numba-dpex->sklearn-numba-dpex==0.1.0.dev0) (0.55.1)
Requirement already satisfied: packaging in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from numba-dpex->sklearn-numba-dpex==0.1.0.dev0) (21.3)
Requirement already satisfied: joblib>=1.1.1 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from scikit-learn->sklearn-numba-dpex==0.1.0.dev0) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from scikit-learn->sklearn-numba-dpex==0.1.0.dev0) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from scikit-learn->sklearn-numba-dpex==0.1.0.dev0) (1.7.3)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from numba<0.56,>=0.54.0->numba-dpex->sklearn-numba-dpex==0.1.0.dev0) (0.38.1+0.g650c36d.dirty)
Requirement already satisfied: setuptools in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from numba<0.56,>=0.54.0->numba-dpex->sklearn-numba-dpex==0.1.0.dev0) (65.6.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/username/miniconda3_wsl/envs/dppy-dev/lib/python3.9/site-packages (from packaging->numba-dpex->sklearn-numba-dpex==0.1.0.dev0) (3.0.9)
Building wheels for collected packages: sklearn-numba-dpex
  Building wheel for sklearn-numba-dpex (pyproject.toml) ... done
  Created wheel for sklearn-numba-dpex: filename=sklearn_numba_dpex-0.1.0.dev0-py3-none-any.whl size=7284 sha256=c1ce1c9e31872545e0b990b8a2ce520e9ff5f343be21bc293d468a526bdb68cc
  Stored in directory: /home/username/.cache/pip/wheels/9c/49/69/06110ec83c2803d5cdeaadd5318c80946a8c6574a3e6737dcb
Successfully built sklearn-numba-dpex
Installing collected packages: sklearn-numba-dpex
Successfully installed sklearn-numba-dpex-0.1.0.dev0
```

Now I am getting ModuleNotFoundError at line #167 of kmeans.py:

```
$ python kmeans.py
Traceback (most recent call last):
  File "/home/username/code/inria/sklearn-numba-dpex/benchmark/kmeans.py", line 167, in <module>
    from sklearn_numba_dpex.testing.config import override_attr_context
ModuleNotFoundError: No module named 'sklearn_numba_dpex.testing
```

But `python -c "import sklearn_numba_dpex"` works Ok now.

**Comment by jjerphan** [comment]
Hi @Vika-F,

Thank you for reporting the problems.

Can you provide the results using verbose mode?
```bash
pip install --verbose .
```

**Comment by fcharras** [comment]
It's actually an issue I've noticed too, let me open a quick PR to fix that.

By mistake we've code that enforces `pytest` requirement.

Currently the workaround is installing pytest

`pip install pytest`

**Comment by Vika-F** [comment]
Re-installing `sklearn_numba_dpex` in editable mode helped. Now I have no exceptions when running the benchmark.
Thank you very much @fcharras and @jjerphan for helping to resolve this!
I am going to close this issue.

The problem that remains is that the code hangs when it tries to run K-means numba_dpex lloyd on GPU, after this print
`Running Kmeans numba_dpex lloyd GPU with parameters sample_weight=unary n_clusters=127 data_shape=(263256, 14) max_iter=100 tol=0 ...`

Tomorrow I will try to find out at which point of the execution does it hang and maybe open a new issue regarding this.
