### ISSUE TITLE
Code formatting pipeline doesn't seem to work

### ISSUE THREAD

**Issue by fcharras** [soda-inria/sklearn-numba-dpex#64]
Example of output: https://github.com/soda-inria/sklearn-numba-dpex/actions/runs/3541364642/jobs/5945541586

Configuration needed to point to the folders that should be scanned ?

**Comment by jjerphan** [comment]
Indeed, the checked aren't run on the CI.

Adding the `--all-files` option force it to runs everywhere:
```bash
pre-commit run --all-files
```

I will do a PR.

**Comment by jjerphan** [comment]
https://github.com/soda-inria/sklearn-numba-dpex/pull/67 was opened.
